package com.fancymansion.core.common.const

const val MOBILE_SYSTEM_STATUS_BAR_PX = 75
const val MOBILE_SYSTEM_BOTTOM_BAR_PX = 134

const val MOBILE_PREVIEW_NO_SYSTEM_UI_HEIGHT_PX = MOBILE_BASE_SCREEN_HEIGHT_PX - MOBILE_SYSTEM_STATUS_BAR_PX - MOBILE_SYSTEM_BOTTOM_BAR_PX

const val MOBILE_PREVIEW_NO_SYSTEM_UI_HEIGHT_DP = (MOBILE_PREVIEW_NO_SYSTEM_UI_HEIGHT_PX / MOBILE_BASE_SCREEN_DENSITY).toInt()
const val MOBILE_PREVIEW_WIDTH_DP = (MOBILE_BASE_SCREEN_WIDTH_PX / MOBILE_BASE_SCREEN_DENSITY).toInt()
const val MOBILE_PREVIEW_HEIGHT_DP = (MOBILE_BASE_SCREEN_HEIGHT_PX / MOBILE_BASE_SCREEN_DENSITY).toInt()

const val MOBILE_PREVIEW_SPEC = "spec:id=reference_phone,shape=Normal," +
        "width=$MOBILE_PREVIEW_WIDTH_DP," +
        "height=$MOBILE_PREVIEW_NO_SYSTEM_UI_HEIGHT_DP,unit=dp," +
        "dpi=$MOBILE_BASE_SCREEN_DPI"

const val MOBILE_LANDSCAPE_PREVIEW_SPEC = "spec:id=reference_phone,shape=Normal," +
        "width=$MOBILE_PREVIEW_HEIGHT_DP," +
        "height=$MOBILE_PREVIEW_WIDTH_DP,unit=dp," +
        "dpi=$MOBILE_BASE_SCREEN_DPI"

const val TABLET_PREVIEW_HEIGHT_DP = (TABLET_BASE_SCREEN_HEIGHT_PX / TABLET_BASE_SCREEN_DENSITY).toInt()
const val TABLET_PREVIEW_WIDTH_DP = (TABLET_BASE_SCREEN_WIDTH_PX / TABLET_BASE_SCREEN_DENSITY).toInt()

const val TABLET_PREVIEW_SPEC = "spec:shape=Normal," +
        "width=$TABLET_PREVIEW_WIDTH_DP," +
        "height=$TABLET_PREVIEW_HEIGHT_DP,unit=dp," +
        "dpi=$TABLET_BASE_SCREEN_DPI"